version: '3'

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    container_name: mqtt_broker
    volumes:
      - ./mqtt_broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt_broker/data/:/mosquitto/data/
      - ./mqtt_broker/log/:/mosquitto/log/