FROM ubuntu:20.04
LABEL maintainer="Herberto Werner"

ADD ./simplestream.py /scripts/simplestream.py

RUN mkdir spark-events

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk vim iputils-ping && \
    apt-get install --no-install-recommends -y python3.8 python3.8-dev python3.8-venv python3-pip python3-wheel build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install numpy pyspark pandas

ENTRYPOINT ["tail"]
CMD ["-f", "/dev/null"]
